### ISSUE TITLE
Multiple replies.

### ISSUE THREAD

**Issue by lgg2** [Theldus/wsServer#20]
Hello,

If I open the sample .HTML in two or more tabs, connect all instances and send anything, I retrieve a number of "recv" as tabs opened. In the server I see that the tabs are well identified by different FD's.

**Comment by Theldus** [comment]
Hello @lgg2, thanks for the bug report, commit 2a0abeb fixes this.

Before closing this issue, could you confirm that the mentioned commit fixes your problem?

**Comment by lgg2** [comment]
Hello, Thanks for the patch. Tomorrow I will test it. I will say.

**Comment by lgg2** [comment]
Works. Thanks. Can be close.
