### ISSUE TITLE
Maybe not only doing a server?

### ISSUE THREAD

**Issue by haruzheng** [Theldus/wsServer#38]
Hi

I want to using this library to doing a client.
I need to change code or not?

I think maybe need change code can do it, but maybe not?

thank you

**Comment by Theldus** [comment]
Hi @haruzheng,
Unfortunately, this library is just a websocket server, and it doesn't work as a client.

Although the RFC 6455 specs for client and server are very similar, I have no intention (at the moment) to support both in a single project.

If you want to use a websocket client in C, you will have to look for another project.
