### ISSUE TITLE
clang-forma and coding style

### ISSUE THREAD

**Issue by silvioprog** [Theldus/wsServer#6]
Hi.

It would be nice to adopt a coding style and make it formatted automatically by [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html).

WDYT?

**Comment by Theldus** [comment]
Hi @silvioprog,
Indeed, clang-format is an amazing tool, I've played a little with it a few years ago but I never have used it in my development process.

While not having a well-defined and documented coding-style messes a little bit with the collaboration process, I don't know if that would be the case with wsServer, I mean, it's a small project and it is expected to not receive many contributions, so I would say that maybe this is not a concern, just as I don't see many reasons to create issues/pull-requests templates, contributions guidelines and so on...

If I had to adopt a 'coding-style', it would most likely be [this](https://github.com/nanvix/documentation/blob/master/guidelines/coding-style), a project that I had contributed to for a few years and which is the coding-style that I use in my personal projects as well.

So I don't know if the clang-format fits this project, if so, maybe a custom style based on the link above would be the ideal.

**Comment by Theldus** [comment]
Hi @silvioprog,
Just to let you know that now wsServer has a [coding-style](https://github.com/Theldus/wsServer/blob/master/doc/CODING_STYLE.md) and a `.clang-format` file.

Thus, I think that I can close this issue now, thanks for the suggestion, ;-).
