### ISSUE TITLE
<feature> Why not support IPv6

### ISSUE THREAD

**Issue by dukelec** [Theldus/wsServer#80]
(No description needed)

**Comment by Theldus** [comment]
Hi @dukelec,
There's actually a [PR in progress on this](https://github.com/Theldus/wsServer/pull/56), I just need time to review it and merge it.

**Comment by Theldus** [comment]
Hi @dukelec,
IPv6 support has been added in PR #82. I would appreciate it if you could test it and provide your feedback =).
