### ISSUE TITLE
[question]Can messages be send to client outside main thread?

### ISSUE THREAD

**Issue by habi498** [Theldus/wsServer#94]
Hi i am planning to run a websocket server in a separate thread from my main program. I am new to mutex, lock and unique_lock. I have saved the client pointer from 'onmessage' function. Can i safely use ws_sendframe from my main program using this pointer.

**Comment by habi498** [comment]
Hi Theldus, 
Thanks for reply.  Also i will take care not to use client pointer after they disconnect

**Comment by Theldus** [comment]
> Just be careful if your client disconnects... since the list of clients in wsServer is static, **reusing the pointer of a connection that has already been closed may result in sending a message to a client that does not exist, or even to another client**.

Since this is no longer a issue (thanks to PR #96), I'm going to close this. Please feel free re-open it or create new issues if you feel the need =).
