### ISSUE TITLE
HTTP should be case insentive

### ISSUE THREAD

**Issue by jrbenito** [Theldus/wsServer#98]
# What?

Header in HTTP shall be case-insensitive as per [RFC7540](https://httpwg.org/specs/rfc7540.html#HttpHeaders). However, most browser send them  camel cased like `Sec-WebSocket-Version: 13`. Some libraries  and proxies that implement the RFC in a strict fashion do not. For example, HAProxy convert all headers to lower case before sending them out due to HTTP/2 compatibility.

As the RFC puts it:

> Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed ([Section 8.1.2.6](https://httpwg.org/specs/rfc7540.html#malformed)). 

# Issue

The library is checking for the header `Sec-WebSocket-Key` in a case sensitive fashion during the [handshake at line 98](https://github.com/Theldus/wsServer/blob/ea8a029eaccc6369d7b04678ed8dd7c645af42e8/src/handshake.c#L98). The constant is defined at  [ ws.h line 84](https://github.com/Theldus/wsServer/blob/ea8a029eaccc6369d7b04678ed8dd7c645af42e8/include/ws.h#L84); and the [answer defined in line 94](https://github.com/Theldus/wsServer/blob/ea8a029eaccc6369d7b04678ed8dd7c645af42e8/include/ws.h#L94) is camel cased.

When using the library in an application that is situated behind a web proxy like HAProxy, it refuses to connect due to this check.

# Workaround

On HAProxy, a temporary fix is to define `h1-case-adjust sec-websocket-key Sec-WebSocket-Key` and enable the `option h1-case-adjust-bogus-server`. However, this will not work forever when the application using this library is paired with a HTTP/2 web app. 

It also might be impossible to modify a websocket/http client library in some circumstances.

# Suggested fix

Use a case-insensitive string comparison or convert received headers to lower case.

Thanks and best regards!

**Comment by Theldus** [comment]
Hi @jrbenito,
You are absolutely right!
Unfortunately I focused my efforts on RFC 6455 and didn't pay as much attention to HTTP 😅.

I'll think of a fix for this and update the issue, again, thanks a lot.

**Comment by Theldus** [comment]
@jrbenito Commit [da82a69](https://github.com/Theldus/wsServer/commit/da82a69f48571de757194cf6a025f9138deadff7) should fix this. 
Please let me know if this solves your issue.

**Comment by jrbenito** [comment]
Thanks @Theldus , it iseems ok from my side.
