### ISSUE TITLE
[bug]example ping.c hangs when client not respond

### ISSUE THREAD

**Issue by habi498** [Theldus/wsServer#99]
Description
-----------
I was learning about wsServer ping and pong. To test it the ping.exe in examples was run. Then a client (similar to echo.html) was connected. The client have no code to respond to ping messages. When client is connected, server says "Connected". Then after few seconds "Sending ping". If no client was connected, this message appear in every 10 seconds. But when a client is connected and after the first "Sending ping", nothing happens. I disconnected the client and cannot reconnect it. so ping program hangs i suppose.

Your environment
----------------
Describe your environment:
- wsServer version [ea8a029](https://github.com/Theldus/wsServer/commit/ea8a029eaccc6369d7b04678ed8dd7c645af42e8)
- OS version: Windows 10.
  - If Windows:

    - Is it running under MinGW? yes
- Architecture:  x86-64
- Client: Google Chrome
  - If browser: which website?
    - Have you tested under the echo/echo.html example? yes.
<img width="475" alt="ping hang" src="https://github.com/user-attachments/assets/c9e809d2-5488-4ce6-9788-a2f3798b8133">

**Comment by Theldus** [comment]
Hi @habi498,
Thank you for the detailed issue, this definitely looks like a bug.
I'll take a look and keep you updated.

**Comment by habi498** [comment]
Hi @Theldus, this indeed fixes the issue.
